name:
    platybrowser
channels:
    - cpape
    - conda-forge
dependencies:
    - affogato >=0.2.1,<0.3.0
    - cluster_tools >=0.3.2,<0.4.0
    - elf >=0.2.2,<0.3.0
    - mahotas
    - nifty v1.0.7
    - napari
    - paintera_tools >=0.2.2,<0.3.0
    - pandas
    - pybdv >=0.4.1,<0.5.0
    - s3fs
    - scikit-learn
    - z5py >=2.0.5
